vich_uploader:
    db_driver: orm

    mappings:
        personne_image:
            uri_prefix: /images/registre_personnes
            upload_destination: '%kernel.project_dir%/public/images/registre_personnes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        naissance_image:
            uri_prefix: /images/registre_naissances
            upload_destination: '%kernel.project_dir%/public/images/registre_naissances'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
